export const DataOrdenesToday = [
  {
    orden: "00150",
    fecha: "2020/05/12",
    hora: "8:00 am",
    paciente: "Jampier Smith Vasquez Mija",
    servicio: "Prueva Covid 19",
    medico: "Hector Emilio Velasquez",
    status: "Creado",
    link: "Ver mas",
  },
  {
    orden: "00151",
    fecha: "2020/05/12",
    hora: "10:00 am",
    paciente: "Sofia Estrella Ramirez",
    servicio: "Prueba de embarazo",
    medico: "Hector Emilio Velasquez",
    status: "En camino",
    link: "Ver mas",
  },
  {
    orden: "00151",
    fecha: "2020/05/12",
    hora: "10:00 am",
    paciente: "Jampier Smith Vasquez Mija",
    servicio: "Prueba de covid",
    medico: "Hector Emilio Velasquez",
    status: "Completado",
    link: "Ver mas",
  },
];
